# Generated by Django 4.0.4 on 2022-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('drafts', 'Drafts')], default='active', max_length=27),
        ),
    ]
